name: mends-on-fhir

services:
  pre:
    profiles:
      - pre
    image: ${MOF_IMAGE:?err}
    entrypoint: /usr/bin/bash
    command:
      - -c
      - echo =============== sleeping 2 ==================; sleep 2
  demo-1:
    profiles:
      - demo-1
    image: ${MOF_IMAGE:?err}
    command: convert
    user: ${UID_GID:?err}
    depends_on:
      pre:
        condition: service_completed_successfully
        required: false # This is triggering a (false?) warning. See: https://github.com/docker/compose/issues/10851
    volumes:
      - type: bind
        source: ${MOF_SOURCE_DIR:?err}
        target: /whistle

