services:
  fhir-server:
    build:
      context: hapi/build
    environment:
      - "SPRING_CONFIG_LOCATION=file:///hapi-config/application.yaml"
      - "HAPI_URL=${FHIR_URL}"
    healthcheck:
      test: [ "CMD", "curl", "-f", "${FHIR_URL}/metadata" ]
      interval: 30s
      timeout: 30s
      retries: 10
    ports:
      - target: 8080
        host_ip: localhost
        published: 8080
    volumes:
      - type: bind
        source: hapi/config
        target: /hapi-config

