# This is a clone of the load.yaml file in order to add the validate dependency when running the full
# pipeline with the "all" bash scripts. This is a workaround to what I think is a bug in docker compose.
# See the following issue for clarification from their team: https://github.com/docker/compose/issues/10901

services:
  load:
    build:
      context: load/build
    volumes:
      - type: bind
        source: convert/volume/output
        target: /output
    depends_on:
      fhir-server:
        condition: service_healthy
        required: false
      validate:
        condition: service_completed_successfully
        required: false
