# This is a clone of the load.yaml file in order to add the convert dependency when running the full
# pipeline with the "all" bash scripts. This is a workaround to what I think is a bug in docker compose.
# See the following issue for clarification from their team: https://github.com/docker/compose/issues/10901

services:
  validate:
    build:
      context: validate/build
      args:
        USER_UID: ${USER_UID:?err}
        USER_GID: ${USER_GID:?err}
    user: ${UID_GID}
    command:
      - -ig
      - ${VALIDATE_IG:?err}
      - -html-output
      - /validation/results/validation_${NOW}.html
      - -output-style
      - csv
      - -output
      - /validation/results/validation_${NOW}.csv
      - -version
      - "4.0"
      - /validation/resources/*.json
#    network_mode: host
#    dns: ["8.8.8.8"]
    volumes:
      - type: bind
        source: validate/volume/results
        target: /validation/results
      - type: bind
        source: convert/volume/output
        target: /validation/resources

    depends_on:
      convert:
        condition: service_completed_successfully
        required: false
