#!/usr/bin/env bash
#set -x
#set -e  # do not exit on errors
set -u
set -o pipefail
#set -o noclobber
shopt -s  nullglob

# stack overflow #59895
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do
    DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
    SOURCE="$(readlink "$SOURCE")"
    [[$SOURCE != /* ]] && SOURCE="$DIR/$SOURCE"
done
DIR="$(cd -P "$(dirname "$SOURCE")" && pwd)"
DATE=$(date +%y.%m.%d_%H.%M.%S)
LOG_FILE="${DIR}/mends-validate-log_${DATE}.txt"

echo > "${LOG_FILE}" 2>&1

if [ ! -f "${DIR}/validator.jar" ]; then
    curl -L -o validator.jar https://github.com/hapifhir/org.hl7.fhir.core/releases/latest/download/validator_cli.jar  >> "${LOG_FILE}" 2>&1
fi


for file in "${DIR}/"*.json; do
    echo >> "${LOG_FILE}" 2>&1
    echo >> "${LOG_FILE}" 2>&1
    echo =============== Validating "$(basename $file)" $(date) ============================= >> "${LOG_FILE}" 2>&1
    echo ============================================================== >> "${LOG_FILE}" 2>&1
    # documentation: https://confluence.hl7.org/x/tAUhAg
    java -Xmx16G -jar "${DIR}/validator.jar" "$file" \
    -extension any \
    -ig hl7.fhir.us.core#4.0.0 \
    -html-output "${file}_${DATE}.html" >> "${LOG_FILE}" 2>&1
    cp "$LOG_FILE" "${DIR}/mends-validate-log_latest.txt"

    # sleep longer (5 min?) to possibly avoid a rate limit on tx.fhir.org.
    echo sleeping 150 >> "${LOG_FILE}" 2>&1
    sleep 150
done
